"use client";

import type { ToolExecutionLog } from "@sea-ops/schemas";

interface DraftedReply {
  messageId: string;
  buyerName: string;
  problemType: string;
  urgency: string;
  originalMessage: string;
  draftText: string;
  status?: string;
}

interface DraftMetadata {
  agentUsed: string;
  draftSource: string;
  model: string;
  fallbackReason: string;
}

export function DraftedRepliesPanel({ logs }: { logs: ToolExecutionLog[] }) {
  const drafts = logs.flatMap(extractDrafts);
  const metadata = logs.map(extractMetadata).find((item): item is DraftMetadata => Boolean(item));

  return (
    <section className="panel">
      <h2>Drafted Buyer Replies</h2>
      <p className="muted">Review these drafts before approving any send action.</p>
      {metadata ? (
        <p className="muted">
          Generated by {metadata.agentUsed || "BuyerReplyDraftAgent"} · {metadata.draftSource || "unknown"}
          {metadata.model ? ` · ${metadata.model}` : ""}
          {metadata.fallbackReason ? ` · ${metadata.fallbackReason}` : ""}
        </p>
      ) : null}
      {drafts.length === 0 ? <p className="muted">No buyer reply drafts yet.</p> : null}
      <div className="list">
        {drafts.map((draft) => (
          <div className="evidence" key={draft.messageId}>
            <strong>{draft.buyerName} · {draft.problemType.replaceAll("_", " ")}</strong>
            <p className="muted">Urgency: {draft.urgency}{draft.status ? ` · Status: ${draft.status}` : ""}</p>
            <p>{draft.originalMessage}</p>
            <pre>{draft.draftText}</pre>
          </div>
        ))}
      </div>
    </section>
  );
}

function extractMetadata(log: ToolExecutionLog): DraftMetadata | undefined {
  if (log.toolName !== "draftBuyerReply") return undefined;
  const agentUsed = stringValue(log.output.agentUsed);
  const draftSource = stringValue(log.output.draftSource);
  if (!agentUsed && !draftSource) return undefined;

  return {
    agentUsed,
    draftSource,
    model: stringValue(log.output.model),
    fallbackReason: stringValue(log.output.fallbackReason),
  };
}

function extractDrafts(log: ToolExecutionLog): DraftedReply[] {
  if (log.toolName !== "draftBuyerReply") return [];

  const directDrafts = arrayValue(log.output.replyDrafts);
  if (directDrafts.length > 0) return normalizeDrafts(directDrafts);

  const simulator = objectValue(log.output.simulator);
  const stateAfter = objectValue(simulator?.stateAfter);
  const messages = arrayValue(stateAfter?.messages);
  return normalizeDrafts(messages);
}

function normalizeDrafts(items: unknown[]): DraftedReply[] {
  return items.flatMap((item, index) => {
    const draft = objectValue(item);
    if (!draft) return [];

    const draftText = stringValue(draft.draftText) || stringValue(draft.replyDraft);
    if (!draftText) return [];

    return [{
      messageId: stringValue(draft.messageId) || stringValue(draft.id) || `draft-${index}`,
      buyerName: stringValue(draft.buyerName) || "Buyer",
      problemType: stringValue(draft.problemType) || "buyer_message",
      urgency: stringValue(draft.urgency) || "medium",
      originalMessage: stringValue(draft.originalMessage) || stringValue(draft.body),
      draftText,
      status: stringValue(draft.status),
    }];
  });
}

function objectValue(value: unknown): Record<string, unknown> | undefined {
  return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : undefined;
}

function arrayValue(value: unknown): unknown[] {
  return Array.isArray(value) ? value : [];
}

function stringValue(value: unknown): string {
  return typeof value === "string" ? value : "";
}
